[package]
name = "velovite-back"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.6", features = ["postgres"] }
axum = "0.7.9"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1.42.0", features = ["full"] }